[package]
name = "db"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
publish = false
edition = "2018"

[dependencies.sled]
version = "0.19"

[dependencies.failure]
version = "0.1"

[dependencies.failure_derive]
version = "0.1"

[dependencies.rental]
version = "0.5"
